services:
  goodbuy-user:
    image: 'goodbuy-user-image'
    build:
      context: .
    container_name: 'goodbuy-user-container'
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/goodbuy-user-db
      - SPRING_DATASOURCE_USERNAME=goodBuy
      - SPRING_DATASOURCE_PASSWORD=goodBuyUser
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - goodbuy-network
  db:
    image: postgres:latest
    container_name: goodbuy-user-db
    command: -p 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=goodBuy
      - POSTGRES_PASSWORD=goodBuyUser
      - POSTGRES_DB=goodbuy-user-db
    networks:
      - goodbuy-network
networks:
  goodbuy-network:
    external: true